version: '3.9'

services:
  mysql_db:
    image: ${MYSQL_IMAGE:-mysql:latest}
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-my-secret-pw}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mysql1}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    volumes:
      - datadir:/my/own/datadir
      - ${MYSQL_CONFIG_DIR:-./.config/mysql}/sql/30_mysql_initdb.sh:/docker-entrypoint-initdb.d/30_mysql_initdb.sh
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - env_net
    restart: unless-stopped

  adminer:
    image: ${ADMINER_IMAGE:-adminer:latest}
    container_name: adminer_container
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-mysql_db}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-nette}
    ports:
      - ${ADMINER_PORT:-8080}:8080
    networks:
      - env_net
    restart: always

networks:
  env_net:
    external: true
    driver: bridge

volumes:
  datadir: # external: true
